## merge and join

In [1]:
import sqlite3
import csv

import pandas as pd

In [15]:
with sqlite3.connect('data/chinook.db') as connection:
    df_customers = pd.read_sql('select * from customers', con = connection)
    df_invoices = pd.read_sql('select * from invoices', con = connection)

In [16]:
df_invoices

,InvoiceId,CustomerId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,2,2009-01-01 00:00:00,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,1.98
1,2,4,2009-01-02 00:00:00,Ullevålsveien 14,Oslo,NaN,Norway,0171,3.96
2,3,8,2009-01-03 00:00:00,Grétrystraat 63,Brussels,NaN,Belgium,1000,5.94
3,4,14,2009-01-06 00:00:00,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,8.91
4,5,23,2009-01-11 00:00:00,69 Salem Street,Boston,MA,USA,2113,13.86
...,...,...,...,...,...,...,...,...,...
407,408,25,2013-12-05 00:00:00,319 N. Frances Street,Madison,WI,USA,53703,3.96
408,409,29,2013-12-06 00:00:00,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,5.94
409,410,35,2013-12-09 00:00:00,"Rua dos Campeões Europeus de Viena, 4350",Porto,NaN,Portugal,NaN,8.91
410,411,44,2013-12-14 00:00:00,Porthaninkatu 9,Helsinki,NaN,Finland,00530,13.86
411,412,58,2013-12-22 00:00:00,"12,Community Centre",Delhi,NaN,India,110017,1.99

In [17]:
df_joined = pd.merge(df_customers, df_invoices, how='inner', on='CustomerId')
df_joined.head()

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,...,Email,SupportRepId,InvoiceId,InvoiceDate,BillingAddress,BillingCity,BillingState,BillingCountry,BillingPostalCode,Total
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,luisg@embraer.com.br,3,98,2010-03-11 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.98
1,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,luisg@embraer.com.br,3,121,2010-06-13 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,3.96
2,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,luisg@embraer.com.br,3,143,2010-09-15 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,5.94
3,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,luisg@embraer.com.br,3,195,2011-05-06 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,0.99
4,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,...,luisg@embraer.com.br,3,316,2012-10-27 00:00:00,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,1.98

In [18]:
df_joined['InvoiceId'].info()

<class 'pandas.Series'>
RangeIndex: 412 entries, 0 to 411
Series name: InvoiceId
Non-Null Count  Dtype
--------------  -----
412 non-null    int64
dtypes: int64(1)
memory usage: 3.3 KB

In [23]:
numbers = df_joined.groupby(by=['FirstName', 'LastName'])['InvoiceId'].count()

## Outer Join on Movie Data

In [24]:
df_movie = pd.read_csv('data/movie.csv')
df_movie.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [31]:
df_color = df_movie[['director_name', 'color']]
df_critic = df_movie[['director_name', 'num_critic_for_reviews']]
df_color.head()
df_critic.head()
df_left = pd.merge(df_color, df_critic, on='director_name', how='left')
df_full = pd.merge(df_color, df_critic, on='director_name', how='outer')
df_left.shape
df_full.shape

(30300, 3)

In [28]:
df_full

         director_name  color  num_critic_for_reviews
0        A. Raven Cruz  Color                     3.0
1           Aaron Hann  Color                    29.0
2      Aaron Schneider  Color                   160.0
3        Aaron Seltzer  Color                    99.0
4         Abel Ferrara  Color                    48.0
...                ...    ...                     ...
30295              NaN  Color                    75.0
30296              NaN  Color                    11.0
30297              NaN  Color                    23.0
30298              NaN  Color                    11.0
30299              NaN  Color                    43.0

[30300 rows x 3 columns]

In [29]:
df_left

          director_name  color  num_critic_for_reviews
0         James Cameron  Color                   723.0
1         James Cameron  Color                   315.0
2         James Cameron  Color                   210.0
3         James Cameron  Color                    94.0
4         James Cameron  Color                    82.0
...                 ...    ...                     ...
30295  Benjamin Roberds  Color                    13.0
30296       Daniel Hsia  Color                    14.0
30297          Jon Gunn  Color                    11.0
30298          Jon Gunn  Color                    15.0
30299          Jon Gunn  Color                    43.0

[30300 rows x 3 columns]

## Grouping and Aggregating

In [32]:
df_titanic = pd.read_excel('data/titanic.xlsx')
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [35]:
df_pclass = df_titanic.groupby(by='Pclass').agg({'Fare':'sum', 'PassengerId':'count', 'Age':'mean'})
df_pclass

              Fare  PassengerId        Age
Pclass
1       18177.4125          216  38.233441
2        3801.8417          184  29.877630
3        6714.6951          491  25.140620

In [ ]:
df_multilevel = df_movie.groupby(by=['color', 'director_name']).agg({'num_critic_for_reviews':'sum', 'duration':'mean'})

                                    num_critic_for_reviews  duration
color           director_name
Black and White Akira Kurosawa                       153.0     202.0
                Aleksey German                       121.0     177.0
                Alex Garland                         489.0     108.0
                Alexander Payne                      433.0     115.0
                Alfred Hitchcock                     434.0     119.0
...                                                    ...       ...
Color           Zoran Lisinac                         17.0     108.0
                Álex de la Iglesia                    71.0     104.0
                Émile Gaudreault                      67.0      92.0
                Éric Tessier                           9.0      99.0
                Étienne Faure                          9.0      98.0

[2490 rows x 2 columns]

In [39]:
needed_columns = ['Year', 'Month', 'ArrDelay', 'DepDelay']
df_flights = pd.read_parquet('data/flights', columns=needed_columns)
df_flights.head(50)

    Year Month ArrDelay DepDelay
0   2022     4    -9.00   -10.00
1   2022     4    -6.00    -3.00
2   2022     4   -22.00   -12.00
3   2022     4    -5.00    -8.00
4   2022     4   -11.00    -7.00
5   2022     4    -3.00     7.00
6   2022     4    -6.00    -4.00
7   2022     4   -17.00    -8.00
8   2022     4   -27.00   -10.00
9   2022     4   -13.00    -3.00
10  2022     4   -10.00    -8.00
11  2022     4    32.00    34.00
12  2022     4    -5.00   -11.00
13  2022     4   -24.00   -11.00
14  2022     4   -21.00   -12.00
15  2022     4   -26.00   -10.00
16  2022     4   -15.00    -3.00
17  2022     4   -29.00   -12.00
18  2022     4   -36.00    -7.00
19  2022     4   -27.00    -7.00
20  2022     4   -20.00    -6.00
21  2022     4   -20.00    -5.00
22  2022     4   -12.00    -1.00
23  2022     4   -27.00   -10.00
24  2022     4     8.00    -2.00
25  2022     4   -19.00    -6.00
26  2022     4    17.00    -5.00
27  2022     4   -13.00    -5.00
28  2022     4    19.00    22.00
29  2022     4    33.00    26.00
30  2022     4   -14.00    -6.00
31  2022     4   -18.00    -3.00
32  2022     4    44.00    48.00
33  2022     4    28.00    34.00
34  2022     4   -10.00    -6.00
35  2022     4    -4.00     7.00
36  2022     4    -6.00    -4.00
37  2022     4    53.00    56.00
38  2022     4     2.00    -4.00
39  2022     4   -22.00   -11.00
40  2022     4    17.00    23.00
41  2022     4    -6.00    -2.00
42  2022     4   -11.00    -8.00
43  2022     4    35.00    14.00
44  2022     4    65.00    67.00
45  2022     4    -8.00    -8.00
46  2022     4    -2.00    -6.00
47  2022     4    -8.00    -5.00
48  2022     4    -7.00     1.00
49  2022     4    -7.00    -6.00

In [42]:
df_flights['ArrDelay'] = pd.to_numeric(df_flights['ArrDelay'], errors='coerce')
df_flights['DepDelay'] = pd.to_numeric(df_flights['DepDelay'], errors='coerce')

In [43]:
df_periodic = df_flights.groupby(by=['Year', 'Month']).agg(
    avg_arrival = ('ArrDelay', 'mean'),
    max_dep_delay = ('DepDelay', 'max'),
    Total_flights=('Year', 'count')
    )

In [44]:
df_periodic

            avg_arrival  max_dep_delay  Total_flights
Year Month
2022 1         3.981085         2512.0         537902
     10        2.085886         2963.0         572287
     11        4.708015         3433.0         546410
     12       13.767535         3169.0         557095
     2         4.674906         2545.0         495713
     3         7.087064         2966.0         564853
     4         8.579072         2366.0         556502
     5         7.411093         2607.0         578819
     6        10.677201         2994.0         577283
     7         9.856325         2556.0         594957
     8         8.714221         2687.0         589810
     9         2.404789         2872.0         557494

## Applying Functions

In [47]:
def passenger(age):
    if age < 18:
        return 'Child'
    else :
        return 'Adult'
df_titanic['Age_group'] = df_titanic['Age'].apply(passenger)

In [53]:
df_employee = pd.read_csv('data/employee.csv')
df_employee['Normalized salaries']=df_employee.groupby(by='DEPARTMENT')['BASE_SALARY'].transform(lambda x: (x-x.min())/(x.max()-x.min()))

In [55]:
df_movie

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [56]:
def mov_category(duration):
    if duration<60:
        return 'Short'
    elif duration>60 and duration<120:
        return 'Medium'
    else:
        return 'Long'
df_movie['Duration_Category'] = df_movie['duration'].apply(mov_category)
df_movie

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,Duration_Category
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,Long
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,Long
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,Long
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,Long
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,Long
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,Medium
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,Short
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,Medium
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,Medium
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,Medium

In [60]:
df_movie.sort_values(by='imdb_score', ascending=False)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,Duration_Category
2725,Color,John Blanchard,NaN,65.0,0.0,176.0,Andrea Martin,770.0,NaN,Comedy,...,English,Canada,NaN,NaN,NaN,179.0,9.5,1.33,0,Medium
1920,Color,Frank Darabont,199.0,142.0,0.0,461.0,Jeffrey DeMunn,11000.0,28341469.0,Crime|Drama,...,English,USA,R,25000000.0,1994.0,745.0,9.3,1.85,108000,Long
3402,Color,Francis Ford Coppola,208.0,175.0,0.0,3000.0,Marlon Brando,14000.0,134821952.0,Crime|Drama,...,English,USA,R,6000000.0,1972.0,10000.0,9.2,1.85,43000,Long
4312,NaN,John Stockwell,2.0,90.0,134.0,354.0,T.J. Storm,260000.0,NaN,Action,...,NaN,USA,NaN,17000000.0,2016.0,454.0,9.1,NaN,0,Medium
2779,Color,NaN,53.0,55.0,NaN,2.0,Olaf Lubaszenko,20.0,447093.0,Drama,...,Polish,Poland,TV-MA,NaN,NaN,3.0,9.1,1.33,0,Short
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2266,Color,Bob Clark,32.0,88.0,84.0,177.0,Vanessa Angel,650.0,9109322.0,Comedy|Family|Sci-Fi,...,English,Germany,PG,20000000.0,2004.0,384.0,1.9,2.35,0,Medium
4498,Color,A. Raven Cruz,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,...,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128,Medium
2240,Color,Jason Friedberg,111.0,88.0,82.0,329.0,Tony Cox,869.0,14174654.0,Comedy,...,English,USA,PG-13,25000000.0,2008.0,624.0,1.9,1.85,0,Medium
1126,Color,Lawrence Kasanoff,12.0,91.0,11.0,500.0,Larry Miller,719.0,NaN,Action|Animation|Comedy|Family|Fantasy,...,English,USA,PG,65000000.0,2012.0,611.0,1.7,NaN,0,Medium
2789,Color,Jon M. Chu,84.0,115.0,209.0,41.0,Sean Kingston,569.0,73000942.0,Documentary|Music,...,English,USA,G,13000000.0,2011.0,69.0,1.6,1.85,62000,Medium

## Using pipe

In [61]:
def filter_survivors(df):
    return df[df['Survived'] == 1].copy()

def fill_missing_age(df):
    df['Age'] = df['Age'].fillna(df['Age'].mean())
    return df

def calculate_fare_per_age(df):
    df['Fare_Per_Age'] = df['Fare'] / df['Age']
    return df

final_titanic = (
    df_titanic
    .pipe(filter_survivors)
    .pipe(fill_missing_age)
    .pipe(calculate_fare_per_age)
)

final_titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Age_group,Fare_Per_Age
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,Adult,1.875876
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,Adult,0.304808
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,Adult,1.517143
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S,Adult,0.412344
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C,Child,2.147914