## learning

In [2]:
import pandas as pd

data = {
    'Ism': ['Ali', 'Vali', 'Sardor', 'Madina'],
    'Yosh': [25, 30, 22, 28],
    'Shahar': ['Toshkent', 'Samarqand', 'Buxoro', 'Farg\'ona']
}

df = pd.DataFrame(data)
print(df)

      Ism  Yosh     Shahar
0     Ali    25   Toshkent
1    Vali    30  Samarqand
2  Sardor    22     Buxoro
3  Madina    28   Farg'ona

In [12]:
import pyodbc

# Ulanish sozlamalari
server = r'BUNYODJONS\SQLEXPRESS' # Masalan: localhost yoki 192.168.1.1
database = 'exam_preperation'

# Connection string (Ulanish qatori)
# Windows Authentication (parolsiz) bo'lsa:
conn_str = f'DRIVER={{SQL Server}};SERVER={server};DATABASE={database};Trusted_Connection=yes;'

# SQL Server Authentication (login/parol bilan) bo'lsa:
# conn_str = f'DRIVER={{SQL Server}};SERVER={server};DATABASE={database};UID={username};PWD={password}'

try:
    # Ulanishni amalga oshirish
    conn = pyodbc.connect(conn_str)
    cursor = conn.cursor()
    print("Muvaffaqiyatli ulandi!")

    # Ma'lumotlarni o'qish (misol)
    cursor.execute('''
                   SELECT id 
                   FROM dbo.oscar_nominees 
                   where category = 'Best Actor'
                   ''')
    for row in cursor:
        print(row)

    # Ulanishni yopish
    conn.close()

except Exception as e:
    print(f"Xatolik yuz berdi: {e}")

Muvaffaqiyatli ulandi!
(3,)
(4,)
(5,)

In [2]:
import pandas as pd
import seaborn as sns

# 'titanic' datasetini to'g'ridan-to'g'ri DataFrame sifatida yuklab olish
df = sns.load_dataset('titanic')

# Jadvalning dastlabki 5 ta qatorini ko'rish
print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [3]:
import pandas as pd

df = pd.read_csv("spotify-tracks-dataset.csv")

df.head()

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 114000 entries, 0 to 113999
Data columns (total 22 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Unnamed: 0.1      114000 non-null  int64
 1   Unnamed: 0        114000 non-null  int64
 2   track_id          114000 non-null  str
 3   artists           113999 non-null  str
 4   album_name        113999 non-null  str
 5   track_name        113999 non-null  str
 6   popularity        114000 non-null  int64
 7   duration_ms       114000 non-null  int64
 8   explicit          114000 non-null  bool
 9   danceability      114000 non-null  float64
 10  energy            114000 non-null  float64
 11  key               114000 non-null  int64
 12  loudness          114000 non-null  float64
 13  mode              114000 non-null  int64
 14  speechiness       114000 non-null  float64
 15  acousticness      114000 non-null  float64
 16  instrumentalness  114000 non-null  float64
 17  liveness          114000 non-null  float64
 18  valence           114000 non-null  float64
 19  tempo             114000 non-null  float64
 20  time_signature    114000 non-null  int64
 21  track_genre       114000 non-null  str
dtypes: bool(1), float64(9), int64(7), str(5)
memory usage: 18.4 MB

In [5]:
df.describe()

,Unnamed: 0.1,Unnamed: 0,popularity,duration_ms,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
count,114000.000000,114000.000000,114000.000000,1.140000e+05,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000,114000.000000
mean,56999.500000,56999.500000,33.238535,2.280292e+05,0.566800,0.641383,5.309140,-8.258960,0.637553,0.084652,0.314910,0.156050,0.213553,0.474068,122.147837,3.904035
std,32909.109681,32909.109681,22.305078,1.072977e+05,0.173542,0.251529,3.559987,5.029337,0.480709,0.105732,0.332523,0.309555,0.190378,0.259261,29.978197,0.432621
min,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,-49.531000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,28499.750000,28499.750000,17.000000,1.740660e+05,0.456000,0.472000,2.000000,-10.013000,0.000000,0.035900,0.016900,0.000000,0.098000,0.260000,99.218750,4.000000
50%,56999.500000,56999.500000,35.000000,2.129060e+05,0.580000,0.685000,5.000000,-7.004000,1.000000,0.048900,0.169000,0.000042,0.132000,0.464000,122.017000,4.000000
75%,85499.250000,85499.250000,50.000000,2.615060e+05,0.695000,0.854000,8.000000,-5.003000,1.000000,0.084500,0.598000,0.049000,0.273000,0.683000,140.071000,4.000000
max,113999.000000,113999.000000,100.000000,5.237295e+06,0.985000,1.000000,11.000000,4.532000,1.000000,0.965000,0.996000,1.000000,1.000000,0.995000,243.372000,5.000000

# part 1

## task 1

In [32]:
import pandas as pd
import sqlite3
from collections import Counter

In [ ]:


with sqlite3.connect('data/chinook.db') as connection:
    df_customers = pd.read_sql('Select * from customers',
    con = connection
    )
df_customers.head(10)

,CustomerId,FirstName,LastName,Company,Address,City,State,Country,PostalCode,Phone,Fax,Email,SupportRepId
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,0171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5
6,7,Astrid,Gruber,NaN,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,NaN,Austria,1010,+43 01 5134505,NaN,astrid.gruber@apple.at,5
7,8,Daan,Peeters,NaN,Grétrystraat 63,Brussels,NaN,Belgium,1000,+32 02 219 03 03,NaN,daan_peeters@apple.be,4
8,9,Kara,Nielsen,NaN,Sønder Boulevard 51,Copenhagen,NaN,Denmark,1720,+453 3331 9991,NaN,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4

## task 2

In [4]:
df_iris = pd.read_json("data/iris.json")
print(df_iris.shape)
print(df_iris.columns)
print(df_iris)

(150, 5)
Index(['sepalLength', 'sepalWidth', 'petalLength', 'petalWidth', 'species'], dtype='str')
     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

In [11]:
df_iris

     sepalLength  sepalWidth  petalLength  petalWidth    species
0            5.1         3.5          1.4         0.2     setosa
1            4.9         3.0          1.4         0.2     setosa
2            4.7         3.2          1.3         0.2     setosa
3            4.6         3.1          1.5         0.2     setosa
4            5.0         3.6          1.4         0.2     setosa
..           ...         ...          ...         ...        ...
145          6.7         3.0          5.2         2.3  virginica
146          6.3         2.5          5.0         1.9  virginica
147          6.5         3.0          5.2         2.0  virginica
148          6.2         3.4          5.4         2.3  virginica
149          5.9         3.0          5.1         1.8  virginica

[150 rows x 5 columns]

## task 3

In [27]:
df_titanic = pd.read_excel('data/titanic.xlsx')
print(df_titanic.head())

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S

In [16]:
df_titanic

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

## task 4

In [35]:
df_flights = pd.read_parquet('data/flights')

In [19]:
df_flights = pd.read_parquet('data/flights')
df_flights.info()

<class 'pandas.DataFrame'>
RangeIndex: 6729125 entries, 0 to 6729124
Columns: 109 entries, Year to Div5TailNum
dtypes: str(109)
memory usage: 7.1 GB

In [20]:
import gc

del df_flights

gc.collect()

270

## task 5

In [47]:
df_movie = pd.read_csv('data/movie.csv')
print(df_movie.sample(10))

      color       director_name  num_critic_for_reviews  duration  \
284   Color          Tim Burton                   230.0     119.0
704   Color      Frank Darabont                   186.0     189.0
703   Color       David Frankel                   180.0     115.0
2514  Color  Jonathan Liebesman                   196.0      83.0
2127  Color    David Cronenberg                   196.0     115.0
1697  Color        Edward Zwick                    60.0     122.0
1412  Color      Michael Tollin                    74.0     109.0
3158  Color       John Turturro                    36.0     119.0
2910  Color        Cheryl Dunye                    33.0      86.0
4022  Color         Kevin Smith                   254.0     102.0

      director_facebook_likes  actor_3_facebook_likes       actor_2_name  \
284                   13000.0                   567.0     Estella Warren
704                       0.0                   693.0     Jeffrey DeMunn
703                      64.0                   664.0    Kathleen Turner
2514                    473.0                   597.0   Jordana Brewster
2127                      0.0                   716.0       Sarah Polley
1697                    380.0                  2000.0     Morgan Freeman
1412                     19.0                   568.0        Riley Smith
3158                      0.0                    54.0        Ben Gazzara
2910                     17.0                   581.0    Marsha Thomason
4022                      0.0                   387.0  Haley Joel Osment

      actor_1_facebook_likes        gross                            genres  \
284                   1000.0  180011740.0  Action|Adventure|Sci-Fi|Thriller
704                  15000.0  136801374.0       Crime|Drama|Fantasy|Mystery
703                   2000.0  143151473.0               Comedy|Drama|Family
2514                 20000.0   39511038.0                            Horror
2127                  1000.0    2840417.0            Horror|Sci-Fi|Thriller
1697                 18000.0   26830000.0                 Drama|History|War
1412                  1000.0   52277485.0             Biography|Drama|Sport
3158                   816.0     836641.0                             Drama
2910                   873.0   17321573.0                            Comedy
4022                 40000.0    1821983.0               Comedy|Drama|Horror

      ... num_user_for_reviews language  country  content_rating       budget  \
284   ...               1368.0  English      USA           PG-13  100000000.0
704   ...               1377.0  English      USA               R   60000000.0
703   ...                320.0  English      USA              PG   60000000.0
2514  ...                366.0  English      USA               R   16000000.0
2127  ...                527.0  English   Canada               R   31000000.0
1697  ...                365.0  English      USA               R   18000000.0
1412  ...                196.0  English      USA              PG   35000000.0
3158  ...                 40.0  English    Spain               R          NaN
2910  ...                 18.0  English      USA           PG-13          NaN
4022  ...                261.0  English      USA               R    3000000.0

      title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
284       2001.0                  658.0        5.7          2.35
704       1999.0                  745.0        8.5          1.85
703       2008.0                  899.0        7.1          2.35
2514      2006.0                 4000.0        5.9          1.85
2127      1999.0                  900.0        6.8          1.85
1697      1989.0                11000.0        7.9          1.85
1412      2003.0                  762.0        6.9          1.85
3158      1998.0                  623.0        6.2          1.85
2910      2004.0                  691.0        4.5          1.85
4022      2014.0                 3000.0        5.4          2.35

     movie_facebook_likes
284                     0
704                 30000
703                 11000
2514                    0
2127                 6000
1697                    0
1412                    0
3158                   74
2910                  151
4022                20000

[10 rows x 28 columns]

# part 2

## task 1

In [ ]:
columns = [column.lower() for column in df_iris.columns]
df_iris.columns = columns
print(df_iris.columns)
df_iris_subset = df_iris[['sepal_width', 'sepal_length']]
print(df_iris_subset)

Index(['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species'], dtype='str')
     sepalwidth  sepallength
0           3.5          5.1
1           3.0          4.9
2           3.2          4.7
3           3.1          4.6
4           3.6          5.0
..          ...          ...
145         3.0          6.7
146         2.5          6.3
147         3.0          6.5
148         3.4          6.2
149         3.0          5.9

[150 rows x 2 columns]

In [25]:
type(df_iris.columns)

pandas.Index

## task 2

In [ ]:
df_over_30 = df_titanic[df_titanic['Age'] > 30]

counts = Counter(df_titanic['Sex'])

print(counts)

print(df_over_30.head())

    PassengerId  Survived  Pclass  \
1             2         1       1
3             4         1       1
4             5         0       3
6             7         0       1
11           12         1       1

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                            Allen, Mr. William Henry    male  35.0      0
6                             McCarthy, Mr. Timothy J    male  54.0      0
11                           Bonnell, Miss. Elizabeth  female  58.0      0

    Parch    Ticket     Fare Cabin Embarked
1       0  PC 17599  71.2833   C85        C
3       0    113803  53.1000  C123        S
4       0    373450   8.0500   NaN        S
6       0     17463  51.8625   E46        S
11      0    113783  26.5500  C103        S

In [33]:
from collections import Counter

counts = Counter(df_titanic['Sex'])

print(counts)

Counter({'male': 577, 'female': 314})

## task 3

In [41]:
cloumns = [i for i in df_flights.columns]
cloumns

['Year',
 'Quarter',
 'Month',
 'DayofMonth',
 'DayOfWeek',
 'FlightDate',
 'Reporting_Airline',
 'DOT_ID_Reporting_Airline',
 'IATA_CODE_Reporting_Airline',
 'Tail_Number',
 'Flight_Number_Reporting_Airline',
 'OriginAirportID',
 'OriginAirportSeqID',
 'OriginCityMarketID',
 'Origin',
 'OriginCityName',
 'OriginState',
 'OriginStateFips',
 'OriginStateName',
 'OriginWac',
 'DestAirportID',
 'DestAirportSeqID',
 'DestCityMarketID',
 'Dest',
 'DestCityName',
 'DestState',
 'DestStateFips',
 'DestStateName',
 'DestWac',
 'CRSDepTime',
 'DepTime',
 'DepDelay',
 'DepDelayMinutes',
 'DepDel15',
 'DepartureDelayGroups',
 'DepTimeBlk',
 'TaxiOut',
 'WheelsOff',
 'WheelsOn',
 'TaxiIn',
 'CRSArrTime',
 'ArrTime',
 'ArrDelay',
 'ArrDelayMinutes',
 'ArrDel15',
 'ArrivalDelayGroups',
 'ArrTimeBlk',
 'Cancelled',
 'CancellationCode',
 'Diverted',
 'CRSElapsedTime',
 'ActualElapsedTime',
 'AirTime',
 'Flights',
 'Distance',
 'DistanceGroup',
 'CarrierDelay',
 'WeatherDelay',
 'NASDelay',
 'SecurityDelay',
 'LateAircraftDelay',
 'FirstDepTime',
 'TotalAddGTime',
 'LongestAddGTime',
 'DivAirportLandings',
 'DivReachedDest',
 'DivActualElapsedTime',
 'DivArrDelay',
 'DivDistance',
 'Div1Airport',
 'Div1AirportID',
 'Div1AirportSeqID',
 'Div1WheelsOn',
 'Div1TotalGTime',
 'Div1LongestGTime',
 'Div1WheelsOff',
 'Div1TailNum',
 'Div2Airport',
 'Div2AirportID',
 'Div2AirportSeqID',
 'Div2WheelsOn',
 'Div2TotalGTime',
 'Div2LongestGTime',
 'Div2WheelsOff',
 'Div2TailNum',
 'Div3Airport',
 'Div3AirportID',
 'Div3AirportSeqID',
 'Div3WheelsOn',
 'Div3TotalGTime',
 'Div3LongestGTime',
 'Div3WheelsOff',
 'Div3TailNum',
 'Div4Airport',
 'Div4AirportID',
 'Div4AirportSeqID',
 'Div4WheelsOn',
 'Div4TotalGTime',
 'Div4LongestGTime',
 'Div4WheelsOff',
 'Div4TailNum',
 'Div5Airport',
 'Div5AirportID',
 'Div5AirportSeqID',
 'Div5WheelsOn',
 'Div5TotalGTime',
 'Div5LongestGTime',
 'Div5WheelsOff',
 'Div5TailNum']

In [ ]:
print(df_flights[['Origin', 'Dest', 'Carrier']])
print(df_flights['Dest'].nunique())

KeyError: "['Carrier'] not in index"

In [46]:
print(df_flights['Dest'].nunique())

373

## task 4

In [48]:
df_movie.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [51]:
df_over120 = df_movie[df_movie['duration'] > 120]
print(df_over120.sort_values(by='director_facebook_likes', ascending=False))

      color      director_name  num_critic_for_reviews  duration  \
66    Color  Christopher Nolan                   645.0     152.0
3     Color  Christopher Nolan                   813.0     164.0
120   Color  Christopher Nolan                   478.0     128.0
1222  Color  Christopher Nolan                   341.0     130.0
97    Color  Christopher Nolan                   642.0     148.0
...     ...                ...                     ...       ...
3357  Color                NaN                     9.0     142.0
3582  Color                NaN                    10.0     240.0
3799  Color                NaN                     2.0     199.0
4005  Color                NaN                     NaN     197.0
4031  Color                NaN                    10.0     173.0

      director_facebook_likes  actor_3_facebook_likes      actor_2_name  \
66                    22000.0                 11000.0      Heath Ledger
3                     22000.0                 23000.0    Christian Bale
120                   22000.0                 11000.0       Liam Neeson
1222                  22000.0                 19000.0      Hugh Jackman
97                    22000.0                 23000.0         Tom Hardy
...                       ...                     ...               ...
3357                      NaN                   427.0    Jack O'Connell
3582                      NaN                   334.0      Blake Ritson
3799                      NaN                   505.0  Jonathan Crombie
4005                      NaN                   110.0   Jessica De Gouw
4031                      NaN                   476.0        Colm Feore

      actor_1_facebook_likes        gross                            genres  \
66                   23000.0  533316061.0       Action|Crime|Drama|Thriller
3                    27000.0  448130642.0                   Action|Thriller
120                  23000.0  205343774.0                  Action|Adventure
1222                 23000.0   53082743.0     Drama|Mystery|Sci-Fi|Thriller
97                   29000.0  292568851.0  Action|Adventure|Sci-Fi|Thriller
...                      ...          ...                               ...
3357                 27000.0          NaN                     Drama|Romance
3582                   805.0          NaN              Comedy|Drama|Romance
3799                   662.0          NaN                      Drama|Family
4005                   578.0          NaN                         Drama|War
4031                   723.0          NaN            Horror|Sci-Fi|Thriller

      ... num_user_for_reviews language    country  content_rating  \
66    ...               4667.0  English        USA           PG-13
3     ...               2701.0  English        USA           PG-13
120   ...               2685.0  English        USA           PG-13
1222  ...               1100.0  English        USA           PG-13
97    ...               2803.0  English        USA           PG-13
...   ...                  ...      ...        ...             ...
3357  ...                 33.0  English         UK             NaN
3582  ...                 50.0  English         UK             NaN
3799  ...                 74.0  English     Canada            TV-G
4005  ...                  1.0  English  Australia             NaN
4031  ...                 33.0  English        USA             NaN

           budget  title_year actor_2_facebook_likes imdb_score  aspect_ratio  \
66    185000000.0      2008.0                13000.0        9.0          2.35
3     250000000.0      2012.0                23000.0        8.5          2.35
120   150000000.0      2005.0                14000.0        8.3          2.35
1222   40000000.0      2006.0                20000.0        8.5          2.35
97    160000000.0      2010.0                27000.0        8.8          2.35
...           ...         ...                    ...        ...           ...
3357          NaN         NaN                  698.0        7.7           NaN
3582          NaN         NaN                  432.0        8.2          1.78
3799          NaN         NaN                  517.0        8.4          1.33
4005   15000000.0         NaN                  476.0        7.4           NaN
4031          NaN         NaN                  539.0        5.0          1.78

     movie_facebook_likes
66                  37000
3                  164000
120                 15000
1222                49000
97                 175000
...                   ...
3357                    0
3582                    0
3799                    0
4005                  367
4031                  518

[1039 rows x 28 columns]

# part 3

## task 1

In [52]:
df_iris.describe()

       sepallength  sepalwidth  petallength  petalwidth
count   150.000000  150.000000   150.000000  150.000000
mean      5.843333    3.057333     3.758000    1.199333
std       0.828066    0.435866     1.765298    0.762238
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.350000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000

In [55]:
print(df_titanic['Age'].min())
print(df_titanic['Age'].max())
print(df_titanic['Age'].sum())

0.42
80.0
21205.17

In [57]:
director_long = df_movie.groupby('director_name')['duration'].max()
long_director = director_long.idxmax()
print(long_director)

Taylor Hackford

In [61]:
print(df_flights.isna().sum())
mean_delay = df_flights['Depdelay'].mean()
df_flights['Depdelay'] = df_flights['Depdelay'].fillna(mean_delay)
print(df_flights['Depdelay'].isna().sum())

Year                      0
Quarter                   0
Month                     0
DayofMonth                0
DayOfWeek                 0
                     ...
Div5WheelsOn        6729125
Div5TotalGTime      6729125
Div5LongestGTime    6729125
Div5WheelsOff       6729125
Div5TailNum         6729125
Length: 109, dtype: int64

KeyError: 'Depdelay'

['sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species']

In [62]:
df_flights = df_flights.fillna(df_flights.mean(numeric_only=True))

In [63]:
print(df_flights[['DepDelay', 'AirTime']].isna().sum()) # Agar shu nomli ustunlar bo'lsa

DepDelay    177348
AirTime     197113
dtype: int64

In [64]:
df_flights = df_flights.fillna(df_flights.mean(numeric_only=True))

In [65]:
print(df_flights[['DepDelay', 'AirTime']].isna().sum()) # Agar shu nomli ustunlar bo'lsa

DepDelay    177348
AirTime     197113
dtype: int64